org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.87
mod_id=cybercraft
mod_name=Cybercraft: Night City
mod_license=MIT
mod_version=0.1.0
mod_group_id=dev.zhirkovtagir0.cybercraft
